utils.js
While importing the generated SBOM into DependencyTrack, I encountered an error that a SHA-256 hash was too long. After further investigation, I found that the utility is not correctly representing the digest taken from Gopkg.lock, as it is in hex form and not base64 encoded as the `ssri` package expects.
=> Correctly encode the sha256 hash in Gopkg.lock files.

utils.js
Reverts AppThreat/cdxgen#17
Breaking tests. There might be a different issue or a fix.
=> Revert "Correctly encode the sha256 hash in Gopkg.lock files."

index.js
Using `--sbt-dir` to setup `sbt-dependency-graph` has rather serious
limitations that prevent us from initializing sbt and running the
plugin.
Instead, we add the plugin info with `addPluginSbtFile` and run sbt in
the root path of the project.
`dependencyList::toFile` is problematic for multi-project setups because
it prevents us from writing to the same file for subprojects. Using
`--force` will only override the write and save the dependency list from
the last project analyzed, whichever that might be.
I forked the original project and added `--append` to the original
`toFile` subtask to support bulk collection of dependencies.
We "could" instead look at the list of projects and run `dependencyList`
on each of them but that requires cumbersome and fragile sbt output
parsing.
Note1: We …
=> Custom sbt plugin to fetch dependencies

test/gomod/go.mod, utils.js, utils.test.js
This fixes an issue (#59) with parsing go.mod files if they include package
references that end in go. For example, github.com/aws/aws-sdk-go.
The matching against the go.mod file is overly aggressive for keywords
like go in the file. This aggressive matching results in packages
being dropped from the scan.
This change ensures that the start of the line is used
in the matching for go and module keywords. I believe this is safe as
the go.mod files are uniform in construction (at least around these two
areas).
It may be worth making other matches for replace and require more
precise, but that is not part of the scope of this change.
=> Fixes #59 inadvertent dropping of packages ending in go

.github/workflows/dockertests.yml, index.js, test/data/golist-dep.txt, test/data/gomodwhy.txt, test/data/gomodwhynot.txt, utils.js, utils.test.js
Uses go list -deps to get the list and then runs `go mod why -m -vendor` to set scope attribute to required or optional.
```
go list -deps -f '{{with .Module}}{{.Path}} {{.Version}}{{end}}' ./...
```
This makes the resulting BoM more complete and informational.
Fixes https://github.com/AppThreat/cdxgen/issues/62
=> Use go list and mod to improve BoM

index.js
No results were being generated when running with any of the JavaScript types (e.g. -t nodejs/js/javascript/typescript/ts) on a pnpm project. The following check was never passing as utils.parsePkgLock() is an async function returning a Promise
```
if (dlist && dlist.length) {
...
}
```
=> await results when parsing pnpm lock files

index.js, package-lock.json, package.json
Hi, prabhu 
I found the bug when I generate the sbom with gradlew
```sh
$ cdxgen -o bom.json
Executing gradlew dependencies in my-test-project
null null
```
And I fixed it by resolving the path.
```sh
$ cdxgen -o bom.json
Executing /my/absolute/path/gradlew dependencies in my-test-project
BOM file written to bom.json
```
=> Convert relative gradlew path into absolute path

utils.js
Drupal 9 has an empty composer.lock file at `/core/modules/system/tests/fixtures/HtaccessTest/composer.lock`.
This should not prevent the creation of an SBOM.
=> Don't stop on invalid composer.lock file.

index.js
The install had a dash too many and the update was missing the option entirely.
=> Fix composer "--ignore-platform-reqs"

index.js
```
├─ java
│ ├─ app
│ ├─ build.gradle.kts
│ ├─ gradle
│ │ └── wrapper
│ │     ├── gradle-wrapper.jar
│ │     └── gradle-wrapper.properties
│ ├─ gradlew
│ ├─ gradlew.bat
│ ├─ settings.gradle.kts
│ └─ src
├─ kotlin
│ ├─ gradle
│ │ └── wrapper
│ │     ├── gradle-wrapper.jar
│ │     └── gradle-wrapper.properties
│ ├─ gradlew
│ ├─ gradlew.bat
│ ├─ lib
│ │ ├── build.gradle.kts
│ │ └── src
│ └── settings.gradle.kts
```
Without this change, unable to generate a BOM if multiple, unrelated, gradle projects are not in the root
```
$ bin/cdxgen -r -t kotlin  # or java
Executing /home/mike/dev/cdxgen/gradlew dependencies in /home/blyenth/dev/cdxgen/testing/java
null null
Executing /home/mike/dev/cdxgen/gradlew dependencies in /home/blyenth/dev/cdxgen/testing/kotlin/lib
null null
Unable to produce BOM …
```
=> Fix missing pathLib.join when determining to use local gradlew

index.js
Wraps CDXGEN_TIMEOUT_MS in a parseInt statement as this is received from the command line as a String
=> Issue 148:  ERR_OUT_OF_RANGE setting environment variable CDXGEN_TIMEOUT_MS

binary.js, index.js, utils.js
Correctly catches cases where a process may exit with a status other than 1 to indicate failure.
=> Check for non-zero status instead of status = 1

utils.js
Previously, transitive dependencies in the Gradle dependencies output like this:
```
+--- org.postgresql:postgresql -> 42.3.6
```
would not be caught, amongst other patterns.
Improve dependency parsing by using a regular expression, which also improves readability/maintainability over the previous string indexing based parsing.
=> Improve Gradle dependency parsing to catch transitive dependencies

utils.js
According to Microsoft's specification [[1]](https://learn.microsoft.com/en-us/aspnet/web-forms/overview/deployment/web-deployment-in-the-enterprise/understanding-the-project-file) [[2]](https://learn.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild?view=vs-2022) PackageReference element of Microsoft Build Engine project files could contain attributes other than "Include", i.e "Update":
```
<ItemGroup>
<PackageReference Update="Microsoft.Extensions.Logging.Abstractions" Version="3.1.6" />
</ItemGroup>
```
So without this change, there will be an undefined reference exception when trying to parse such ASP.NET project files:
```
TypeError: Cannot read properties of undefined (reading 'includes')
at Object.parseCsProjData (C:\snapshot\cdxgen\utils.js:2451:26)
at createCsharpBom …
```
=> Bug fix: C# project (.csproj) parsing error

test/data/gradle-android-dep.out, utils.js, utils.test.js
Good day
I tried using this tool to generate a BOM for an android project and noticed some strange behavior.
Some of the dependency versions were picked up as "{strictly" instead of the actual version e.g. "1.0.0".
Upon further investigation I noticed that the current parser expects it to be a version number, which in this case it is not.
If you create a new project in Android Studio and run the following command
```
./gradlew :app:dependencies -q --console plain
```
You will notice that some of the output items include the word "{strictly" in the version number
```
+--- androidx.core:core:{strictly 1.7.0} -> 1.7.0 (c)
```
The generated BOM entry looks like this
```
{
"group": "androidx.core",
"name": "core",
"version": "{strictly",
"description": "",
"licenses": [],
"purl": …
```
=> Added support for "strict" gradle dependencies

utils.js
https://github.com/AppThreat/cdxgen/issues/157
When the code searches for gradlew, on windows it never looks for gradlew.bat. It does find gradlew, but that will fail to run in cmd/ps.
Per the request, the same change was made for maven, but I have **no** knowledge of how maven is setup, so this will need to be verified by someone who can, or I'll remove it as I only need gradlew working atm.
I do not have alternate OSs to test this on, so please keep that in mind.
=> on windows, look for the bat versions

index.js
This PR contains two fixes identified when using the new Swift BOM Generation functionality:
- Swift was not included in the createMultiXBom function, so Swift BOMs were not generated in multiProject mode. This patch adds Swift into createMultiXBom matching the pattern of other languages.
- If both Package.resolved and Package*.swift files exist inside a repository, the former were ignored. This patch will evaluate all applicable files.
=> Swift Fixes

utils.js
This fixes #383 by no longer adding any configured GRADLE_ARGS to the :properties-call, because it doesn't accept any parameters!
Would love to see this merged into v8.x as well -- I need 1.4 output...
=> Do not add GRADLE_ARGS to :properties-call

index.js
This fixes #386 by checking if EnvVar GRADLE_DEPENDENCY_TAK is set, and if so, use it (and possible arguments) instead of the default task 'dependencies'
=> Implemented handling of GRADLE_DEPENDENCY_TASK

index.js
This fixes #386 by checking if EnvVar GRADLE_DEPENDENCY_TAK is set, and if so, use it (and possible arguments) instead of the default task 'dependencies'
This is a back-port for v8.6.x, since patching didn't quite work
=> Implemented handling of GRADLE_DEPENDENCY_TASK on v8.6.x

utils.js, utils.test.js
Fully relying on the order of versions returned by pypi doesn't always work and sometimes leads to incorrect version resolution.
For example, when solving version ">4,<4.1" for https://pypi.org/pypi/django/json returns 4.0b1 instead of 4.0.10. The reason for this is that pip sorts parsed versions (while pypy sorts "raw" strings).
This PR should solve some version resolution issues
=> Fix python version resolution

contrib/piptree.py, index.js, piptree.js, utils.js, utils.test.js
@ajmalab @cerrussell  could you kindly test and review this PR?
@Hritik14 Could you test #411 with this?
=> Makes pnpm work without breaking docker and repotests. 1 Breaking change

index.js, utils.js
Closing #431 
Pass parentComponent to mergeDependencies.
=> Fixes Issue 431, incorrect parsing of dependencies

test/data/gradle-android-app.dep, test/data/gradle-properties-android.txt, utils.js, utils.test.js
Fixes #448 
Handles root project with unknown version (Eg: :app (*))
@ptrkaz Could you kindly test this PR?
@ajmalab We added filtering of root projects named `app` for one of your test cases called java-test. Any idea what the original issue was? Could you check this branch against other gradle projects?
=> Do not ignore root project named app. 

README.md, bin/cdxgen.js
Enabled self-verification if the public key file is present
Fixes #440 
@troy256 could you let me know if you require samples in any other language?
=> Adds jws verification example to the readme. 

test/data/gradle-android-jetify.dep, utils.js, utils.test.js
Fixes #464: Updated the regex to support 'relocation' of a complete component, not just the version.
=> Fixes #464: Updated the regex to support 'relocation' of a complete component

index.js, utils.js, utils.test.js
This PR corrects the way Gradle sub-projects are handled:
1) it uses the correct `group` -- there was a mismatch between the objects, so the dependency-tree was incorrect
2) if the scan is started on a sub-project instead of on the root, any references to other projects would not be visible as these projects were not included in the list of components/dependencies
Now, sub-projects are simply handled as if they were normal components/dependencies and in the case of scanning from the root of a multi-project, the duplicate components are removed.
Seeing how testing would need a combination of methods from `index.js` and `utils.js`, I wasn't sure how to go about this.
=> Handle Gradle sub-projects correctly

.github/workflows/repotests.yml, README.md, analyzer.js, bin/evinse.js, bin/repl.js, bin/verify.js, display.js, evinser.js, evinser.test.js, index.js, package-lock.json, package.json, utils.js
Sample output for juice shop
[out.txt](https://github.com/CycloneDX/cdxgen/files/12388939/out.txt)
```shell
node bin/cdxgen.js -t js -o bom.json
node bin/evinse.js -i bom.json -o bom.evinse.json -l javascript --with-data-flow -p
```
https://discord.gg/pF4BYWEJcS
=> Evinse for js - part 2 - callstack, vue and svelte

evinser.js, evinser.test.js, index.js, test/data/gradle-properties-sm.txt, test/data/gradle-sm.dep, utils.js, utils.test.js
Fixes #474 
We need to thoroughly test with multiple gradle projects including android
=> Retain parent group and component across sub-projects. Fixes #474 again

.github/workflows/appimage.yml, .github/workflows/dockertests.yml, .github/workflows/nodejs.yml, .github/workflows/repotests.yml, bin/cdxgen.js, bin/verify.js, evinser.js
@troy256, could you help test the new single binary builds and the granular signing (each component is signed in addition to the document)?
You can download the executable from the workflow run.
https://github.com/CycloneDX/cdxgen/actions/runs/5944361616
To do
=> Granular signing. sae builds from verify

README.md, utils.js
feat: allow user to overwrite URL of Maven Central for metadata fetching (e.g. when private repos are used)
=> feat: allow Maven Central URL overwrite

index.js
fixes https://github.com/CycloneDX/cdxgen/issues/517
=> fix: increase buffer for bazel output to avoid incomplete SBOM

README.md, utils.js
Allow to customize the Maven prefix for Bazel (new env variable `BAZEL_STRIP_MAVEN_PREFIX`) as current default `/maven2/` might not work for proxy repos like Nexus OSS
=> feat: allow to customize the Maven prefix for Bazel

README.md, bin/cdxgen.js
```diff
-      --version                Show version number                     [boolean]
-  -h                           Show help                               [boolean]
+  -h, --help                   Show help                               [boolean]
+  -v, --version                Show version number                     [boolean]
```
This would at least help me to figure out the root cause in the future :) (like #521 )
=> chore: add `--help` and `-v` support for help and version output

package-lock.json, package.json, test/data/package-json/v1/package-lock.json, test/data/package-json/v1/package.json, test/data/package-json/v2-workspace/app/package.json, test/data/package-json/v2-workspace/package-lock.json, test/data/package-json/v2-workspace/package.json, test/data/package-json/v2-workspace/scripts/package.json, test/data/package-json/v2/package-lock.json, test/data/package-json/v2/package.json, test/data/package-json/v3/package-lock.json, test/data/package-json/v3/package.json, utils.js, utils.test.js
In a similar vein to https://github.com/CycloneDX/cdxgen/pull/539, this adds real direct dependency information for package-lock.json files.
I introduced a new package [@npmcli/arborist](https://www.npmjs.com/package/@npmcli/arborist?activeTab=readme) to help with package lock parsing. The main difference here is that to get accurate parsing which includes workspaces, a package.json is required in addition to a package-lock.json. I update the test data to include sample package.json and package-lock.json.
The current version of this pkgLock parser doesn't correctly set deps for node workspaces. For example here's the before/after for `./test/data/package-json/v2-workspace` showing the difference for the workspace `app`
I have a complete diff [here](https://www.diffchecker.com/BlssZ2je/). …
=> Fix npm package deps tree

index.js, utils.js, utils.test.js
Closes #529 
Changes:
- Removed setting licenses based on perceived namespaces
- Added replacing of incorrect/nonspecific versions with nuget metadata
- Optimized getting license/nuget metadata by only requesting once after all cs files have been processed and duplicates removed.
- Used existing functions mergeDependencies and trimComponents instead of removeDuplicates.
- Create default parentComponent if it doesn't exist.
=> Fixes Issue 529 Nuget Package Handling

index.js, utils.js, utils.test.js
Currently, pkgList is updated inline via reference, while dependencies are copied with a fresh copy returned. Since javascript doesn't have multiple returns this wasn't immediately evident.
I have tried to improve this and also ran prettier 3.0.3.
=> Refactor code to return an object

README.md, ci/Dockerfile-deno, contrib/deno/README.md, docs/CLI.md
Adding the "gid" flag to successfully build the cdxgen-deno docker image (CI).
Ref: https://docs.deno.com/runtime/manual/basics/permissions#permissions-list
GH Issue: https://github.com/CycloneDX/cdxgen/issues/558
=> Adding the "gid" flag to successfully build the cdxgen-deno docker image (CI).

index.js
As only type and name are mandatory, we can omit empty author, publisher, and description and still be spec-compliant.
Fixes #556
=> Omit empty properties

index.js, utils.js
Adds a simple mode when parsing package json to skip extended attributes and license fetching
Fixes #570
=> Adds a simple mode when parsing package json 

test/data/package-json/v2-workspace/package-lock.json, test/data/package-json/v2-workspace/package.json, test/data/package-json/v2/package-lock.json, utils.js, utils.test.js
Package-lock, starting in version 2, optionally provides package licenses that should be incorporated into BOM generation.
=> Add NPM License Support from Package-Lock v2+

.github/workflows/dockertests.yml, .github/workflows/repotests.yml, docs/ADVANCED.md, package-lock.json, package.json, utils.js, utils.test.js
With this PR, I could run evinse on Windows for an Android with gradle application. Install Android Sdk and set ANDROID_HOME before running evinse.
On my machine, the SDK got installed under `\AppData\Local\Android\Sdk`
https://github.com/home-assistant/android
=> Use shell for windows command invocations

.github/workflows/repotests.yml, index.js, utils.test.js
this breaks PackageURL.fromString from packageurl-js when the version contains e.g. a +
fixes https://github.com/CycloneDX/cdxgen/issues/589
=> fix: remove purl decoding

server.js
Ensure repoUrl username/password and query parameters aren't including within any logs or directory names
=> feat: safely log git url

.github/workflows/repotests.yml, index.js
This uses the piptree-based dependency tree construction, which captures more indirect dependencies (at least double) that may not be present in the poetry lock file.
Also added poetry normal and deep tests to repotest to showcase the difference.
=> Enable deep mode for poetry 

package-lock.json, package.json, utils.js, utils.test.js
Fixes #631 
@robaliias could you kindly test this branch.
=> Trim dotnet sbom by tracking resolved versions

utils.js, utils.test.js
Expand the package name, version tracking by keeping a separate entry for each target framework.
Fixes an issue where package dependency versions were incorrect when different target frameworks contained different versions of the package.
=> Fix dotnet project.assets dependency tree

server.js, utils.js
**Server:**
Added support for branch selection when scanning the repository - gitBranch, specified along with other parameters in the request to /sbom
Fixed an error due to which the server did not process the GIT URL (delete URLs from console.log)
**JS analysis --required-only**
Now, when using the --required-only parameter, if imports of transitives of potential required dependencies were found in the files, then such a dependency is considered required, its imports are also placed in occurrences
In required dependencies, occurrences now also come across imports of transitives from this dependency (additional enrichment)
=> fix required-only,add girBranch to server

data/lic-mapping.json, utils.js
I've found that license information of mvn packages may be stored in at least 4 ways (so far cdxgen used only the fist one).
* in the field `licenses.license` of the POM document
* in the field `licenses.license` of another POM document (defined by the `parent` field of the POM).
* as a comment in the POM.xml
* in the github repo specified in the POM document
I've implemented
* merging POM witht the parent POM
* regexping pom in search of license text
* querying the repo (if specified in POM)
* I've improved the way github api address is deduced from repo address - so that now it accepts more patterns.
=> Fix fetching licenses for jvm packages

server.js
Previously parsing a `type` argument/param was not being correctly passed through
=> fix: correctly set projectType option

.eslintrc.cjs, bin/cdxgen.js, evinser.js, package-lock.json, package.json
With the new atom and this PR, we can resolve the routes and add endpoints to the generated BOM for dependency track.
Related: https://github.com/DependencyTrack/dependency-track/pull/3181
=> Enhance route detection for java with latest atom

evinser.js
Fixes #714 by simplifying array type and limiting the DB lookup to just once per type.
=> Handle shaded usages better

.github/workflows/repotests.yml, utils.js
Another improvement for standalone jar files
1. Optimized extract jar to only spawn "META-INF" directory
2. First checks if pom.properties is available - see: https://maven.apache.org/shared/maven-archiver/index.html
4. Fallback to old logic if pom.properties is not available
Steps to reproduce:
1. Download [org.jacoco.report-0.8.8.jar](https://repo1.maven.org/maven2/org/jacoco/org.jacoco.report/0.8.8/org.jacoco.report-0.8.8.jar), [xmlschema-core-2.2.5.jar](https://repo1.maven.org/maven2/org/apache/ws/xmlschema/xmlschema-core/2.2.5/xmlschema-core-2.2.5.jar), [jackson-core-2.16.0.jar](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.16.0/jackson-core-2.16.0.jar), [junit-4.13.2.jar](https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar), …
=> Improved detection for standalone jar files by using pom.properties file if available

docs/SERVER.md, index.js, server.js
- Correct project to projectId in server.js. This should just pass through now and match, though anyone who's using the old param will have to move to the new one.
- Handle DT requirement of having project ID OR name/version. If you are missing the ID and the name or version, then it'll reject the BOM. Pop a log message and return early if we are missing it.
- Pass in parentUUID if running from server.js. When looking at the projectId I noticed we're not actually catching the parentUUID from the server side. I left this naming alone even though it's slightly different from ParentId.
- Update SERVER.md. There wasn't anything in for project (which got renamed to projectId), and added in all the other parameters that the server supports so they are no longer undocumented. Also added an …
=> Fixes for Server params 

.github/workflows/repotests.yml, utils.js
@prabhu fixed & refactored loading pom.properties. If you can provide the link to the jar file which included 'META-INF/maven/extension.xml' I can add it to the test as well.
=> Fixed & refactored loading pom.properties

.github/workflows/repotests.yml
1. I splitted the big repotests step into multiple smaller steps.
2. `-p` flag added were it was missing
3. Ensured each result is written into bomresults folder
4. Ensured unique naming of output file
5. More consistent flag vaules (true/false vs 0/1)
6. ` ls -ltr bomresults` after all steps writing bom files into this folder
This should help to identify long running repotests or were problems exactly occured.
=> Refactor repotests

.github/workflows/repotests.yml, utils.js
1. In case the maven wrapper is found but is not ready or functioning, make sure the fallback to initially assumed "mvn" command works.
2. spawnSync returns an ``error`` object only in case child process is timed out or the invocation itself fails. Read ``status`` as well to ensure that the child process executed successfully
=> Ensure fallback to system maven works

.github/workflows/repotests.yml
Fixed following repositories to specific tag:
- flutter/gallery: v2.10.2
- gojek/ziggurat: 4.9.4
- apple/swift-markdown: 0.3.0
- GoogleCloudPlatform/microservices-demo: v0.8.1
- zoom/meetingsdk-vuejs-sample: v2.18.0
- openpbs/openpbs: v23.06.06
- home-assistant/android: 2023.11.3
- rust-lang/rust: 1.74.0
- rust-lang/cargo: 0.75.0
- Keats/validator: v0.15.0
- tokio-rs/axum: axum-v0.6.20
- fsprojects/FAKE: 6.0.0
- appthreat/blint: v1.0.34
- DefectDojo/django-DefectDojo: 2.28.2
Following repositories are still pulling default branch:
- ShiftLeftSecurity/shiftleft-java-example
- ShiftLeftSecurity/shiftleft-ts-example
- ShiftLeftSecurity/shiftleft-go-example
- prabhu/shiftleft-scala-example
- HooliCorp/vulnerable_net_core
- HooliCorp/Goatly.NET
- HooliCorp/DjanGoat
- …
=> Fixed microservices-demo to tag v0.8.1

README.md
The `sudo` is not needed and it's misleading as if was required
=> doc: remove sudo from npm install documentation

docker.js, docker.test.js, index.js
This PR addresses a few items that weren't fully aligned with the [oci pURL spec](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#oci)
These include
- `name` must be lowercased
- `name` is the last fragment from a repository name (eg: `library/debian` is `debian`)
- optional qualifiers `tag` can be added
- `repository_url` optional qualifier should be the `registry` + `name` combined
- component `type` explicitly set to `container` instead of `library`
=> feat: enhance oci purl spec compliance

utils.js
`parsePnpmLock` crach with the following error when parsing a `pnpm-lock.yaml` without a packages field.
```
file:///opt/node/lib/node_modules/@cyclonedx/cdxgen/utils.js:1299
const pkgKeys = Object.keys(packages);
^
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at parsePnpmLock (file:///opt/node/lib/node_modules/@cyclonedx/cdxgen/utils.js:1299:28)
at createNodejsBom (file:///opt/node/lib/node_modules/@cyclonedx/cdxgen/index.js:1995:32)
at async createMultiXBom (file:///opt/node/lib/node_modules/@cyclonedx/cdxgen/index.js:4620:15)
at async createBom (file:///opt/node/lib/node_modules/@cyclonedx/cdxgen/index.js:5663:16)
at async file:///opt/node/lib/node_modules/@cyclonedx/cdxgen/bin/cdxgen.js:377:20
```
=> parsePnpmLock: handle files with no packages field

index.js, utils.js
cdxgen crach when analyse a scala repository where the project dir isn't at the root directory. The following directory structure can be used to reproduce the bug. 
```
/git/test/
└── src
└── scala
├── build.sbt
├── project
│   ├── build.properties
```
This is happening because `determineSbtVersion()` function is being called against the root dir [here](https://github.com/CycloneDX/cdxgen/blob/d9953876572280cd82ec2d967d7cbc11c31175e3/index.js#L1721C28-L1721C47) and it can't find the `build.properties` file. cdxgen crash with the following error:
```
Scanning /git/test/
Detected sbt version: null
/opt/node/lib/node_modules/@cyclonedx/cdxgen/node_modules/semver/classes/semver.js:19
throw new TypeError(`Invalid version. Must be a string. Got type "${typeof version}".`)
```
With this PR if …
=> cdxgen crash when scala project isn't at repository root dir

index.js, package-lock.json, package.json
We have multiple things working against us when it comes to java + maven projects.
1. We recurse by default. Many maven projects can only be built from a specific directory (rootPath)
2. We run the maven plugin in aggregate bom mode to reduce false negatives. Many projects can support such aggregation only from specific base modules.
3. There could be 100s of other factors that could prevent Maven from working smoothly, such as weather, etc.
For now, this PR moves several console.log within an if condition to tune down the logs for multi-module projects.
cc: @heubeck
=> Do not log maven errors for multi-module projects by default

README.md, bin/cdxgen.js, bin/verify.js, binary.js, deno.json, docker.js, docs/CLI.md, docs/README.md, evinser.js, index.js, package-lock.json, package.json, server.js, utils.js, utils.test.js, validator.js
Removes xml output in v10 release
https://github.com/CycloneDX/cdxgen/discussions/459
Fixes https://github.com/CycloneDX/cdxgen/issues/207
cc: @heubeck
=> Remove xml format

index.js
Repository_url qualifiers that contain arguments/variables aren't particularly useful, and can contribute to purl length issues. #872
=> feat(oci): skip adding repository_url qualifier when they contain arguments/variables

utils.js, utils.test.js
I found an api to retrieve the licenses.
I only tested via the npm run test.
- Replace list, if by a find
- Extract license with /api/packages/<package_name>/score json
```json
{
"grantedPoints": 130,
"maxPoints": 140,
"likeCount": 511,
"popularityScore": 0.9982012522051956,
"tags": [
"publisher:dart.dev",
"sdk:dart",
"sdk:flutter",
"platform:android",
"platform:ios",
"platform:windows",
"platform:linux",
"platform:macos",
"platform:web",
"runtime:native-aot",
"runtime:native-jit",
"runtime:web",
"is:null-safe",
"is:wasm-ready",
"is:dart3-compatible",
"license:bsd-3-clause",
"license:fsf-libre",
"license:osi-approved"
],
"lastUpdated": "2024-02-13T13:42:27.418719"
}
```
#891
=> feat(utils): retrieve licenses for Dart packages

index.js, package-lock.json, package.json, utils.js
Related to #795 
When there is no integrity available, the dependency tree is incomplete. With this PR, the location attribute is used as a fallback to solve and complete the tree.
=> Fallback to location based lookups for npm when integrity is unavailable

.github/workflows/repotests.yml, index.js, package-lock.json, package.json, utils.js, utils.test.js
Fixes #937
@scrocquesel could you check this PR and let me know if the version numbers are still correct for project.assets.json and packages.lock.json based projects? Do you have the test case to reproduce the warnings mentioned in this [comment](https://github.com/CycloneDX/cdxgen/issues/930#issuecomment-2016229907)?
```shell
export CDXGEN_DEBUG_MODE=debug
git clone https://github.com/CycloneDX/cdxgen
cd cdxgen
git checkout fix/issue-937
npm install
node bin/cdxgen.js -t csharp -o bom.json ...
```
=> Safely get the resolved version for nuget

index.js
With this PR, csproj files will always get restored. This handles the cases where a project might exist but not referred in any solution files. Also improved the log messages for couple of scenarios.
=> Include csproj files during restore

binary.js, ci/Dockerfile, ci/Dockerfile-deno, index.js, package-lock.json, package.json
=> Bundle dotnet sdk 8

analyzer.js
I came across a Node component that was located in the "__mocks__" folder, but was still specified as scope: "required". It turned out that there is no ignoring in cdxgen for a similar directory. This directory has been added
=> Adding directories starting with __ to ignore

index.js, package.json, utils.js
Solution to https://github.com/CycloneDX/cdxgen/issues/907.
Generating sboms for larger Gradle projects with many sub-projects was quite slow. One of the reasons for this is that `cdxgen` was running the `dependencies` task individually for each sub-project in series. This is extremely slow as there's the added overhead of starting and stopping Gradle and other associated bootstrapping overhead. 
One solution to this slowness is to utilise Gradle's multi-threading support and run the `dependencies` tasks in parallel. In this PR we: 
- We pass in the necessary flags to enable multi-threading in Gradle
- Split the resulting output to individual sub-project dependency task output
- Feed the resulting output into the existing sbom generation logic. 
This achieves a significant performance …
=> Add support for executing dependencies task in parallel for Gradle

.github/workflows/npm-release.yml
Fixes #1045 
Splits workflows into multiple separate jobs.
=> [fix] seperate npm-release to seperate jobs

README.md, docs/PROJECT_TYPES.md, docs/_sidebar.md
Add a new page to the website which documents supported `project types`.  
Migrate content from `README.md` into docs/ to reduce duplication.
=> docs: add project types

README.md
Create a `Documentation` section which has quicklinks to the root level page @ https://cyclonedx.github.io/cdxgen
=> docs: add documentation section

bin/cdxgen.js, bin/evinse.js, bin/verify.js, docs/CLI.md
full terminal width rendered docs awkwardly.
pairing back to 120 chars (default is 80)
=> feat: increase yargs terminal width

.github/workflows/nodejs.yml, .github/workflows/repotests.yml, .vscode/settings.json, README.md, binary.js, ci/Dockerfile-deno, contrib/deno/README.md, deno.json, docs/CLI.md, index.js, utils.js, utils.test.js
Added troubleshooting tips for dealing with private modules in go projects. Tested with this [repo](https://github.com/go-training/golang-private-module). Added a property to represent `indirect` dependencies, since we are currently misusing the `scope` attribute.
Also fixes #1093
=> Improved troubleshooting for go

.github/workflows/dockertests.yml, docker.js, docker.test.js
So far I receive error `Error: TAR_ENTRY_INVALID: checksum failure` instead of the `Error: TAR_ENTRY_INVALID: linkpath forbidden`.
in #572 
However, the changes should take into account both of these.
Also Handles: `TAR_ENTRY_ERROR`, `TAR_ENTRY_UNSUPPORTED` and `TAR_ABORT`
=> Fix: Handle TAR_ENTRY_INVALID error

index.js
We are faced with the fact that cdxgen does not generate SBOM for a project where the `package.json` file exists at the root, but the `package-lock.json` file is missing. In this case, the `installDeps` dependency installation flag does not initiate the installation of dependencies.
We have implemented the installation of dependencies with npm for the case when:
1) There is a `package.json` file in the root of the project.
2) The `package-lock.json` file is missing in the root of the project.
3) `installDeps` flag is set to true.
=> Adding The Installation Of Root Dependencies For Npm

.github/workflows/dockertests.yml
Should fix error 
```
write /var/lib/docker/tmp/GetImageBlob3521541071: no space left on device
Error: Process completed with exit code 1.
```
in github jobs https://github.com/CycloneDX/cdxgen/actions/runs/9163811259/job/25193729491
=> Fix: Split linux-tests job into two jobs

bin/repl.js, display.js, types/display.d.ts, types/display.d.ts.map
```
❯ node /mnt/work/CycloneDX/cdxgen/bin/repl.js sbom-java.vdr.json
██████╗██████╗ ██╗  ██╗
██╔════╝██╔══██╗╚██╗██╔╝
██║     ██║  ██║ ╚███╔╝
██║     ██║  ██║ ██╔██╗
╚██████╗██████╔╝██╔╝ ██╗
╚═════╝╚═════╝ ╚═╝  ╚═╝
✅ SBOM imported successfully from sbom-java.vdr.json
💭 Type .print to view the SBOM as a table
cdx ↝ .vulnerabilities
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                               Vulnerabilities                                                               ║
║                                                         Generated with ♥  by cdxgen                                                         ║ …
```
=> Adds new vulnerabilities command to the repl

index.js
Updated the fallback lookup of BOM files to find JSON files that either contain "bom" or "cdx" in their filename.
Linked to https://github.com/CycloneDX/cdxgen/issues/1126
=> Fallback on 'cdx' or 'bom' JSON files for Java BOM

.github/workflows/dockertests.yml, .github/workflows/repotests.yml, bin/cdxgen.js, display.js, types/display.d.ts, types/display.d.ts.map
Active CycloneDX sponsors can pass the argument `--no-banner` to turn this off.
=> Adds donation message to CI invocations

.github/workflows/snapshot-tests.yml, test/diff/diff_tests.py, test/diff/repos.csv
- I have ugraded the functionality in custom-json-diff to better handle bom diffing
- Handles [version issue](https://github.com/CycloneDX/cdxgen/discussions/1099#discussioncomment-9549267)
- Produces an HTML report in addition to the JSON
- Comparison is of defined bom objects which allows for better control for different use cases
- Will pass if the newly generated bom has the same components or dependencies at equal or greater versions. This also means that purl and bom-ref will not be used in the comparison given they will not be the same in such a scenario.
- Will pass if the snapshot bom has empty fields and the newly generated bom has populated these fields
- Includes licenses, properties, and evidence in comparison but not hashes
@prabhu @setchy I have tested with the snapshots, …
=> Update snapshot tests to integrate new custom-json-diff functionality.

.github/workflows/snapshot-tests.yml, test/diff/diff_tests.py, test/diff/generate.py
Simply changes the directory that we clone our snapshot boms into and where we produce our new snapshot boms so that it is obvious which file in the diff is the original.
=> Clearer paths for new vs old snapshots.

ci/Dockerfile, ci/Dockerfile-bun, ci/Dockerfile-deno, ci/Dockerfile-ppc64
some npm packages such as phantomjs appears to use [bzip2](https://github.com/Medium/phantomjs/blob/master/lib/util.js#L101) to decompress dependencies.
=> Adds bzip2 to containers

test/diff/README.md, test/diff/diff_tests.py
This PR adds some documentation about the snapshot tests and allows for inputting alternative paths for the original and new snapshots. This will be helpful when snapshots in cdxgen-samples need to be updated.
=> Feat: Improve dev-friendliness for snapshot tests.

test/gradle-dep-parallel.out, test/gradle-prop-parallel.out, utils.js
Some Gradle projects have additional tasks that run when running `properties` or `dependencies` tasks in parallel. These tasks were being captured and causing sbom gen to break on some gradle projects when using the multi-threaded mode. [Gradle composite builds](https://docs.gradle.org/current/userguide/composite_builds.html) are a good example of when this might occur. 
This PR fixes it by ignoring irrelevant tasks's outputs when building the output map split by sub-projects.
cc: @prabhu
=> Add if conditional to ignore irrelevant tasks

utils.js
Currently there's no maxBuffer set for running the parallel properties task, and this results in the buffer size defaulting to 1MB, causing some output to be cut-off, especially for large projects. This PR sets the buffer size to 10MB to fix this problem.
cc: @prabhu
=> Add 10MB buffer for parallel Gradle properties task output 

README.md, bin/cdxgen.js, deno.json, docs/CLI.md, jsr.json, lib/server/openapi.yaml, package.json, server.js, types/server.d.ts.map
Both of these query parameters are valid:
```
lifecycle=pre-build
installDeps=false
```
Tested with:
```
curl "http://127.0.0.1:9090/sbom?path=/Volumes/Work/sandbox/server-lifecycle&type=python&lifecycle=pre-build" > bom.json
curl "http://127.0.0.1:9090/sbom?path=/Volumes/Work/sandbox/server-lifecycle&type=python&installDeps=false" > bom.json
```
=> Added support for lifecycle and other args to server

server.js
Add project name to log statements to make it easier to debug
=> feat(server): improve logging

utils.js
`defaultProps` definition was missing from the `executeParallelGradleProperties` method, causing SBOM gen to fail on some repos. This PR fixes it.
=> Add missing variable defaultProps

test/data/conan.with_custom_pkg_user_channel.lock, test/data/conanfile.with_custom_pkg_user_channel.txt, utils.js, utils.test.js
When `cdxgen` parses `conan.lock` files, it fails to detect Conan packages whose [reference](https://docs.conan.io/1/cheatsheet.html#package-terminology) specifies [user and channel attributes](https://docs.conan.io/1/reference/conanfile/attributes.html#user-channel). 
Consider the following `conan.lock` file, where the listed package's reference does not specify *user and channel*. This sample is similar to a [conan.lock](https://github.com/CycloneDX/cdxgen/blob/be4e4f424a984fc96cd63173d14cd13098dd2865/test/data/conan.lock#L15) already present in test data. When running `cdxgen -t cpp .`, the created `bom.json` reflects the package accurately:
```json
/* excerpt from conan.lock */
{
"graph_lock": {
"nodes": {
"0": { /* ... */ },
"1": {
"ref": …
```
=> Allow Conan references with user and channel in conan.lock files

binary.js
**BUG**: Trivy casts error `Unable to initialize the Java DB: Java DB update failed: Java DB update error: '--skip-java-db-update'  cannot be specified on the first run` when running cdgxgen >= 10.4.3 with command `cdxgen --output backend_bom.json --type java --fail-on-error`
on docker images eclipse-temurin:21-jdk-alpine with Java applications packaged as .war. 
**FIX**: Disable Java scanning with Trivy for all Java archive files, not only .jar
=> add all java archive files to trivy skip statement

test/data/Dockerfile, utils.js, utils.test.js
[`FROM` instructions support variables that are declared by any `ARG` instructions that occur before the first `FROM`.](https://docs.docker.com/reference/dockerfile/#understand-how-arg-and-from-interact)
I've added envsubst-a-like behaviour for image name parsing using default values of the `ARG` instructions.
=> Add support for build arguments in FROM instruction

.github/release.yml
per https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
Use the "standard" labels to group release notes into sections. closes #1311 
Would love to discuss if other label groups like lang:* etc are of interest, and if so, how would they appear in a changelog 🤔 
separately, we can discuss adopting something like https://github.com/fuxingloh/multi-labeler, which i've used in other projects (see [gitify-app/gitify](https://github.com/gitify-app/gitify)) to automatically apply labels based on a pretty powerful config file (for the purposes of ensuring all PRs are labels for release note bliss)
=> build: use labels for changleog release section generation

utils.js
When I test cdxgen on [SteamTools](https://github.com/BeyondDimension/SteamTools) repo on C# I get "TypeError: Cannot read properties of null (reading 'match')" on
const match = inputStr.match(extractNameOperatorVersion);
line 7383
=> fixed null error in utils.js

utils.js
`composer.lock` files may have a dependency package version as a number instead of a string (see: https://github.com/google/osv-scanner/issues/1138).
In that case `new PackageURL(...)` throws the following error: `Error: Invalid purl: "versions" argument must be a string.`
By forcing the number to be interpreted as a string (with `.toString()`), the error disappears. The same string conversion is done for the version generated in the SBOM as it should also be a string.
=> Make sure composer.lock dependency package version is a string

index.js, utils.js
This PR fixes issues in the `purl` and `bom-ref` when your module names use characters other than letters or numbers.
I found that some of my modules (generated by expo) had names like 'expo-modules-core$android-annotation-processor', which were sometimes correctly percent encoded in the `purl` and sometimes they weren't. Same with the `bom-ref`, which actually caused cdxgen to output (only in debug):
```
===== WARNINGS =====
[
'Invalid ref in dependencies.dependsOn pkg:maven/host.exp.exponent/expo-modules-core%24android-annotation-processor@1.1.1?type=jar',
'Invalid ref in dependencies.dependsOn pkg:maven/host.exp.exponent/expo-modules-core%24android-annotation@1.1.1?type=jar'
]
```
I do wonder though why the incorrect `purl` wasn't a problem in the validation process...
=> [Gradle] Fixed incorrect PURLs & BOM-REFs

README.md, deno.json, docs/CLI.md, docs/README.md, envcontext.test.js, jsr.json, package.json, pregen.js
Fix `nvm tests` in `envcontext.test.js`.
It should test the following functions:
1) `getNvmToolDirectory`
2) `getOrInstallNvmTool`
4) `isNvmAvailable`
there are some issues here as CircleCI does not actually have `nvm` but does have `NVM_DIR` in `env`.
=> Fix: `nvm tests` in `envcontext.test.js`

index.js, utils.js, utils.test.js
We build apps using Expo, which adds several modules to our build. Currently, these modules are added several times as components with different groups and versions. This PR addresses this by loading the correct data for all modules and caching it to use whenever a module is referenced instead of relying on incorrect defaults.
This PR is based on #1337, which must therefore be resolved before this can be merged.
=> [Gradle] Correctly identify all modules' group and version

utils.js
When using the feature `GRADLE_MULTI_THREADED` on large projects, the output of the dependency-tree can be mangled and there is no guarantee the same SBOM is generated between multiple runs!
To fix this, I added the parameter '--no-parallel' to the Gradle-command, which in my tests didn't show a significant difference in duration. The output SBOM however was consistent every time, although in one of the projects there is a difference with the non-multithreaded version in the versions of dependencies!
Unfortunately this is caused by Gradle itself -- manual inspection of the outputs of all commands shows, that Gradle is actually reporting different versions of dependencies for some modules in the project! I *assume* this is something similar to Maven: because there can only be 1 version of …
=> [Gradle] Don't use full multi-threading, SBOMs can be completely wrong

.github/workflows/repotests.yml, index.js
When resolving the Gradle modules from NPM packages, there was an issue when the package was scoped. Because the package was referenced by its name, which in Gradle gets its scope added, the call to resolve dependencies used the wrong module-name.
=> [Gradle] Fixed a problem with scoped NPM packages while resolving modules from NPM

index.js
After adding the option to resolve Gradle modules from NPM packages and adding the new SBOM in Dependency-Track, I noticed the components didn't have licenses set. Checking the actual packages if they actually have licenses configured, I found that the licenses were removed on sub-components of the root component.
This PR fixes this issue and uses the same method(s) to convert the 'temporary' objects to their correct SBOM counterparts.
I just noticed this removes all code that fixed #479, but all tests are still running and my projects also work like before... If anybody has some Gradle projects they could run through it before we merge, that would be great!
=> Handling sub-components of the root component the same as all other components

biome.json, deno.json, package.json, pnpm-lock.yaml
Updated pnpm, biome, atom, and typescript. New [atom](https://www.npmjs.com/package/@appthreat/atom/v/2.0.20) is a bit more leaner.
=> Typescript 5.6.x with the latest atom

lib/helpers/utils.js, lib/helpers/utils.test.js, test/data/pnpm-lock6b.yaml
Based on discussion in #1359, We now add dependencies for additional components found in `importers` section of `pnpm-lock.yaml`.
=> Feat: Include components from pnpm-lock.yaml importers

lib/cli/index.js
As described in the issue https://github.com/CycloneDX/cdxgen/issues/1370 the newest release of cdxgen will match on non-bazel projects f.ex when finding `build.gradle` files. Changing the search to look for `WORKSPACE`, `WORKSPACE.bazel` and `MODULE.bazel` files.
=> search only for Bazel workspace and module files

lib/cli/index.js, lib/helpers/utils.js
This fixes both the duplicate properties (#1401) and, for Gradle, the usage of a project name as a profile.
The issue for the duplicate properties was not in Gradle-specific code, so this could influence/fix issues with duplicate properties for other languages/tools as well!
=> Duplicate properties

.github/workflows/repotests.yml
This PR fixes the problem with the usage of custom-json-diff in elasticsearch repotest.
=> Added parameter for new version of CJD

test/diff/requirements.txt
This PR bumps the CJD version to 2.1.x, which included bugfixes for circumstances currently causing snapshot tests to fail when they should pass (e.g. #1426).
=> Bump cjd version for bugfixes.

.github/workflows/app-release.yml, .github/workflows/appimage.yml, .github/workflows/binary-builds.yml, .github/workflows/npm-release.yml, .github/workflows/nydus-demo.yml
Fixes https://github.com/CycloneDX/cdxgen/issues/1437.
All GitHub actions that are not triggered by `pull_request` event should not be run on forks.
=> Run some GitHub action jobs only on main repository

.github/workflows/snapshot-tests.yml, test/diff/diff_tests.py
This PR adds a command-line option to handle the change to CycloneDX 1.6 for the snapshot tests. When the original snapshot is v1.5, the data will be migrated to v1.6 if the `--migrate-legacy` argument is given when running diff_tests.py.
=> Enable CycloneDX 1.5 snapshots to be compared with 1.6.

.github/workflows/repotests.yml, .github/workflows/snapshot-tests.yml, test/diff/diff_tests.py, test/diff/generate.py, test/diff/repos.csv
1. Snapshot testing to expand coverage for the following build scenarios:
- java: bazel and gradle (maven already covered)
- nodejs: npm, yarn, pnpm
2. Configuration changes necessary to run the tests on a self-hosted runner
3. Convenience args to include/exclude tests by language or project
=> Expand snapshots part I

lib/helpers/utils.js
- Avoids triggering an exception for referencing an invalid index in `parseCmakeLikeFile`.
- Removes message indicating to the user that they need to install virtualenv (regardless of whether virtual environment creation failed). We are using _venv_ which is a subset of virtualenv that has been part of the Python standard library since Python 3.3.
=> Fix Index Boundary Error in parseCmakeLikeFile

docs/ml_profiles.md
This pull request adds detailed documentation for the Machine Learning (ML) profiles available in `cdxgen`, including:
- `ml-tiny`
- `machine-learning` (`ml`)
- `deep-learning` (`ml-deep`)
The documentation highlights the purpose, settings, post-generation behaviors, and use cases of each profile. Additionally, it explains the `requiresContextTuning` and `requiresContextTrimming` behaviors for better understanding of the profiles' output modifications.
1. **Added a new section in the documentation**:
- Overview table comparing ML profiles.
- Detailed description for each profile, including settings and post-generation behaviors.
- Example scenarios for practical usage of each profile.
- Explanation of `requiresContextTuning` and `requiresContextTrimming`.
2. **Formatted the documentation …
=> Added documentation for ML profiles in cdxgen

lib/cli/index.js
=> fix:GH-1502 name root from package json

contrib/cdxgenGPT/cdxgen-for-bots.md, contrib/cdxgenGPT/rate-my-xbom.md
JSON schema validation and linting are just so old school. Let's teach cdxgenGPT to evaluate and rate BOMs.
=> Rate my xbom

ci/base-images/cdxgen/Dockerfile.dotnet6, ci/base-images/cdxgen/Dockerfile.dotnet7, ci/base-images/cdxgen/Dockerfile.dotnet8, ci/base-images/cdxgen/Dockerfile.dotnet9, ci/base-images/cdxgen/Dockerfile.java, ci/base-images/cdxgen/Dockerfile.java-slim, ci/base-images/cdxgen/Dockerfile.java17, ci/base-images/cdxgen/Dockerfile.java17-slim, ci/base-images/cdxgen/Dockerfile.node20, ci/base-images/cdxgen/Dockerfile.python, ci/base-images/cdxgen/Dockerfile.python310, ci/base-images/cdxgen/Dockerfile.python311, ci/base-images/cdxgen/Dockerfile.python36, ci/base-images/cdxgen/Dockerfile.python39, ci/base-images/cdxgen/Dockerfile.rolling, ci/base-images/cdxgen/debian/Dockerfile.dotnet6, ci/base-images/cdxgen/debian/Dockerfile.dotnet8, ci/base-images/cdxgen/debian/Dockerfile.dotnet9, deno.json, jsr.json, package.json
=> Bundle locally built cli in the container images

lib/cli/index.js, lib/helpers/utils.js, lib/helpers/utils.test.js, test/data/pubspec.lock
The pubspec for dart was an older version. Since 2.15 the sha256 is included in the lock file. Used it to add hashes to the output, along with scope and the dependencies
I updated the pubspec parsing to load it as a yaml to avoid manually having to keep track of the package
I had dart update the example pubspec file
=> Add hash, scope and deps to dart

lib/cli/index.js
A while back, I added a feature for Gradle-projects to resolve their dependencies from Node. Now, with the correct implementation of multi-language SBOMs, these dependencies were added twice. This fix removes any duplicates -- both components and dependencies by merging them into the existing ones.
=> Remove duplicates when resolving Gradle dependencies from Node

bin/cdxgen.js
This fixes #1583 by setting 'installDeps' to default to true, but not override it when it is set from the CLI.
=> Setting 'installDeps' to default to true

.github/workflows/snapshot-tests.yml
Fix the issue #1531 
By installing setuptools and wheel before installing requirements.txt
=> fix: install setuptools and wheel before installing requirements

ci/Dockerfile, ci/Dockerfile-secure, ci/base-images/debian/install.sh, contrib/fine-tuning/Modelfile, contrib/fine-tuning/README.md, contrib/fine-tuning/convert-gguf.sh, contrib/fine-tuning/fine-tune-mlx.sh, contrib/fine-tuning/upload-hf.sh
Switched to llama.cpp master for gguf conversion and Q8_0 quantization. Works on my machine.
```
❯ ollama create cdx1-gguf -f Modelfile
gathering model components
copying file sha256:39ef2abdaad48bdbd1a8466c85b14a9646caf8049ec62e2b8d6383c56e035dc9 100%
parsing GGUF
using existing layer sha256:39ef2abdaad48bdbd1a8466c85b14a9646caf8049ec62e2b8d6383c56e035dc9
using autodetected template chatml
using existing layer sha256:a9f47bf267b28cae24d9d2b7e1d9204045da3b72568e4dcf5f66968e9d1fdf18
using existing layer sha256:de1eea7f14a061696a1490b000e7c36b45bb768c07a236acc828c69580770887
creating new layer sha256:6ee123ab45fc93d2d4223e606e0866d49b943b3826853a5db46fed97cdc50001
writing manifest
success
```
```
❯ ollama show cdx1-gguf
Model
architecture        llama
parameters          14.7B
context …
```
=> Switch to llama.cpp for gguf conversion

.github/workflows/build-base-images.yml
Workaround for the qemu crashes when building arm64 images.
https://github.com/CycloneDX/cdxgen/issues/1602#issuecomment-2656299584
Related: https://github.com/docker/buildx/issues/1169
=> Fix docker qemu bug

package.json
Fixes: https://github.com/CycloneDX/cdxgen/issues/1682
=> fix: correct types path

package.json
Fixes this typescript error:
```
Could not find a declaration file for module '@cyclonedx/cdxgen'. '.../node_modules/@cyclonedx/cdxgen/lib/cli/index.js' implicitly has an 'any' type.
There are types at '.../node_modules/@cyclonedx/cdxgen/types/lib/cli/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@cyclonedx/cdxgen' library may need to update its package.json or typings.ts(7016)
```
We were not exporting types 🤷🏼
=> chore: fix exports

ci/Dockerfile-deno
The deno image currently does not run as the sqlite bindings are not defined. 
Normally this would occur in the post install scripts.
Tiny change to ensure these run.
=> fix(ci-deno): allow sqlite post-install scripts

lib/cli/index.js, lib/helpers/utils.js
cdxgen didn't generate SBOM for Gradle on Windows. This PR fixes this.
Since Windows also has a maximum character count in the CLI, this was also fixed. This unfortunately means that generating a gradle SBOM on Windows could be slower, because we potentially have to run multiple commands instead of just the one!
=> [Gradle] SBOM generation didn't work on Windows

docs/ENV.md, lib/cli/index.js
Mill is very fast when the server is running. Depending on your use-case though, cdxgen can be faster when NOT using it.
2 new EnvVars where added to control usage of the server, defaulting to NOT using it.
Testing was done with CI in mind: running cdxgen on a fresh check-out from SCM.
When running during development and the server is already running, the fastest setting is (obviously) to use the server and not shut it down afterwards.
=> [mill] Added the possibility to control usage of the server (daemon)

lib/cli/index.js
The previously implemented optimization on detecting included/composite builds broke cdxgen when run on a module instead of the root of the project. This PR fixes this and re-adds the optimization when the included/composite modules are entered directly from the cli.
=> [Gradle] Optimization for included/composite builds broke cdxgen on single module

lib/helpers/utils.js
Use `PackageURL.fromString` to properly parse npm `targetName`.
Noticed this when running locally and it picked up a new version of `PackageURL` that validates than `name` cannot contain special characters like `@babel/core`. This allows for parsing the `namespace` and `name` components
=> Use PackageURL.fromString to properly parse npm targetName

ci/base-images/opensuse/Dockerfile.rolling
OpenSuse has removed v1.81 of rust & cargo, so we upgraded to the latest available version: 1.86
=> [build] Update/rust cargo

.github/workflows/build-images.yml, .github/workflows/build-rolling-image.yml
The rolling image has been having some issues lately, because of changes in the OpenSuse repo. I extracted the rolling image into its own workflow so it doesn't abort the other builds when it fails.
=> [build] Extracted the rolling image into its own workflow

.github/workflows/npm-release.yml, ci/Dockerfile, ci/Dockerfile-deno, ci/Dockerfile-secure, ci/base-images/al9/Dockerfile.ruby-builder, package.json, pnpm-lock.yaml
By building Ruby in a separate builder first, we speed up the image builds for the default, secure, and deno images.
=> Build Ruby in a builder

.github/workflows/image-build.yml, bin/verify.js, deno.json, jsr.json, lib/managers/oci.js, package.json, types/lib/managers/oci.d.ts, types/lib/managers/oci.d.ts.map
cdx-verify can be used to verify the SBOM attached in container images.
=> Verify oci images with SBOM attachments

ci/base-images/sle/Dockerfile.node20
The node20-image is failing to build, because it tries to install `npm`, which is already installed!
=> [build] Don't try to install NPM -- it's already installed

.github/workflows/image-build.yml, contrib/free_disk_space.sh
- Removing some more large packages
- 'apt remove' fails when a package does not exist -- explicitly deleting single packages
- Reverse sort, so largest packages are at the top
=> [build] Free more space on CI-machine

lib/helpers/utils.js, test/gomod/go.mod
`tab` is valid char as a sperater for go.mod
i wonder if runing `go mod edit --fmt` before parse `go.mod` will be a better way
=> fix: unformatted go.mod which is valid leads to parse error

.github/workflows/npm-release.yml, ci/Dockerfile, ci/Dockerfile-bun, ci/Dockerfile-deno, ci/Dockerfile-ppc64, ci/Dockerfile-secure, ci/base-images/al10/Dockerfile.ruby-builder, deno.json, jsr.json, package.json
Upgrade to almalinux 10. The new images are much cleaner with just python 3.12 (without the 3.9 bloat). cdxgen-secure and cdxgen are now identical differing only in some environment variables such as NODE_OPTIONS.
=> almalinux 10 upgrade

.github/workflows/build-images.yml, .github/workflows/build-rolling-image.yml
- 30min and less are built in the cloud
- the rest are built on hosted servers, even if that means they are even slower
So far, several images build faster on hosted, some are the same.
Because we currently only use a single hosted server, there's a bit of a queue there though, but at least we don't use up all cloud compute so fast...
=> [build] Moved image-builds between cloud and hosted servers

lib/stages/postgen/postgen.js
Normalize evidence.identity field for consistent processing across CycloneDX versions
In different versions of CycloneDX, the evidence.identity field can be either:
* a single object, or
* an array of objects.
This inconsistency can lead to runtime issues when iterating over the field. To resolve this, this PR introduces a utility function normalizeIdentities(comp) that ensures evidence.identity is always treated as an array, allowing for safe iteration.
**Added**: normalizeIdentities(comp) function to normalize the evidence.identity field.
**Updated**: Replaced direct iteration over comp?.evidence?.identity || [] with normalizeIdentities(comp) to handle both single-object and array formats consistently.
* Prevents potential runtime errors or missed identity data.
* Ensures …
=> bugfix: normalize component evidence identities to always be array

.github/workflows/binary-builds.yml, ci/Dockerfile
Workaround the current github actions limitations with alpine containers.
```
JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64
```
=> musl arm64 builds

.github/workflows/npm-release.yml
We [lost](https://github.com/CycloneDX/cdxgen/discussions/1720#discussioncomment-13495181) a self-hosted agent. With this PR, we move a couple of builds back to GitHub hosted to give us some breathing space.
=> Move containers and containers-secure back to github-hosted

.github/workflows/nodejs.yml, README.md, bin/cdxgen.js, bin/repl.js, contrib/cloud-init.txt, contrib/lima/cdxgen-ubuntu.yaml, deno.json, docs/CLI.md, lib/helpers/protobom.js, lib/helpers/protobom.test.js, package.json, pnpm-lock.yaml, types/lib/helpers/protobom.d.ts.map
Upgraded protobuf dependencies and made proto-related cli arguments public, so people can start using. Attached zip includes the cdxgen BOM is json and .proto format. 410 KB vs 107 KB.
[bom.zip](https://github.com/user-attachments/files/20818839/bom.zip)
Might need some effort to make things compatible with protobuf libraries in other languages, but its time to try this.
=> proto upgrade

.github/workflows/rebuild-release-images.yml
This PR fixes #1884 for the last 2 tags. Every Sunday during the night, all images for the last 2 tags will be rebuilt.
As we have noticed today, we can't guarantee that these images will build correctly, seeing some of the versioned packages we install might not be available any more in the distro's repo.  😞
=> [images] Implemented rebuild for the last 2 tags

renovate.json
Configured renovate to wait for packages to be at least 3 days old before updating to them, so we don't have bleeding edge updates and also possibly fall into the 72 hours unpublish period of the NPM-registry.
=> [renovate] configured minimumReleaseAge

renovate.json
This rule _should_ update github action versions to semver
=> config(renovate): pin github actions

.dockerignore
** on the top of .dockerignore file includes everything. We manually exclude some file/directories. Debian images installs required deps using `install.sh`. Without it, the build will fail
=> Exclude install.sh from .dockerignore

renovate.json
Renovate is removing the checksum and some other configs from the pnpm-lockfile for its updates, which makes our checks fail. This PR tries to fix this by having renovate run 'pnpm i' after updating bur before comitting the changes.
=> [renotavate] Addded 'postUpgradeTasks' to renovate, to have it generate a correct pnpm-lock

.github/workflows/fix-renovate-pnpm-checksum.yml
When a node dependency is updated, this PR will post a comment to the triggering PR with the output of `pnpm why <dependency>`, so we can directly see where it is used and if/what might be influenced by this update.
=> [renovate] Adding a comment to the PR that explains the usage of the updated dependency

.github/actions/build-docker-image/action.yml, .github/actions/build-docker-images-generate-attach-sboms/action.yml, .github/actions/generate-attach-sbom/action.yml
I noticed in the logs that buildx exports the image to the docker daemon as a tarball. Because cdxgen then exports the image from the daemon to a tarball again, I figured we could just export to a tarball right away and save some time on our workflows.
=> [build] Do not load docker image into local registry, export a tarball instead

.github/workflows/binary-builds.yml, .github/workflows/dockertests.yml, .github/workflows/java-reachables-test.yml, .github/workflows/nodejs.yml, .github/workflows/npm-release.yml, .github/workflows/nydus-demo.yml, .github/workflows/python-atom-tests.yml, .github/workflows/repotests.yml, ci/images/alpine/Dockerfile.node24
Locked node v24 to v24.3 because of a regression in v24.4. This seems to be an issue related to using pnpm and having large dependencies: https://github.com/pnpm/pnpm/issues/9743
This PR should be reverted as soon as a newer version of node (or pnpm?) is released that fixes the problem!
=> [build] Fixed regression with node v24.4.0

lib/cli/index.js
=> default to npm when lock file is missing

.github/workflows/repotests.yml, devenv.nix
Node v24.4.0 is now also in the nix repos and making our builds fail. Downgraded to v22 until the regression is patched.
=> [devenv] Downgraded node to v22 because the regression of v24 is now also in the nix repos

bin/cdxgen.js, lib/helpers/envcontext.js, lib/helpers/utils.js
The implementation just added only supported NodeJS and was calling the binary to check. This version is fully implemented in JavaScript and can handle Deno and Bun as well.
=> JS-implementation of getting runtime + version

.github/workflows/test-nodejs-nightly.yml
To pro-actively figure out if we will be having issues with new versions of node and also to figure out when those issues are solved in case they were released, we added a workflow to tries to run 'pnpm install' daily, using the latest nightly build.
=> Testing Node.js nightly builds

contrib/fine-tuning/Modelfile, contrib/fine-tuning/Modelfile-pro, contrib/fine-tuning/convert-gguf.sh, contrib/fine-tuning/fine-tune-mlx.sh, contrib/fine-tuning/upload-hf.sh, contrib/xBOMEval/results/README.md, contrib/xBOMEval/results/cdx1/results-0810/README.md, contrib/xBOMEval/results/cdx1/results-0810/logic.json
cdx1, being our first fine-tune, became the victim of poorly configured fine-tune settings which negatively affected its benchmark results. This is entirely my fault.
For the second attempt, I used Qwen3-coder-480B and gave it the model card of the base model, unsloth template fixes, and relevant code snippets from mlx-lm lora.py and fuse.py to arrive at a suggestion for a lora fine-tuning configuration. It happily suggested a full fine-tune of the base 14B model. Unfortunately, our Mac Minis have only 64GB RAM, making it impossible to perform a full fine-tune. However, I was able to tune all the 48 layers up from the original 16.
The last question was identifying the parameters for inference. Unlike the Qwen3 models, Qwen2.5 surprisingly had no recommendation for these parameters …
=> cdx1 retune

lib/cli/index.js
this debug log statement could disclose sensitive arguments passed via `MVN_ARGS`.  simplifying the log statement
=> fix: dont log mvn dependency:tree args

lib/helpers/utils.js
Changelog:
- Add check for malformed percent-encoding sequences before calling validate-iri
- Replace %prettyVersion% placeholders with actual versions in composer.lock
- Prevents cdxgen from hanging when processing BookStack and similar PHP projects
The validate-iri library hangs indefinitely on URLs with invalid percent-encoding like %prettyVersion% where %pr is not a valid hex sequence. This fix detects such malformed sequences early and also replaces known placeholders with actual version strings.
Fixes issue with packages from Codeberg that use URL placeholders.
See issue #2174
=> Fix validate-iri hanging on malformed percent-encoding

.github/workflows/image-build.yml, .github/workflows/nodejs.yml, .github/workflows/repotests.yml
Noticed another 2 workflows that are ran on self-hosted runners -- changed these to use the inhouse Nexus as well.
The internal network has been updated with a DNS entry for the Nexus server, so IPs have been replaced with the new DNS entry.
=> [build] Updated some more workflows to use Nexus when run on self-hosted runners

lib/cli/index.js
Fixes #2157.
Spec before 1.6 only supports `author` attribute, so it had to be converted from modern format.
=> Convert metadata/component to 1.5

contrib/jupyter-notebook-example/README.md, contrib/jupyter-notebook-example/setup.sh, lib/cli/index.js
**This PR fixes a `TypeError` in `postgen.js` when analyzing mixed Python/JavaScript projects with `--type python`.**
- When processing the root `pyproject.toml`, a component is created in `lib/cli/index.js` without setting the `SrcFile` property.  
- Later, this component reaches `relativeDir()` in `postgen.js`,  where `SrcFile` is `undefined` , causing: 
`TypeError: Cannot read properties of undefined (reading 'startsWith')`
- Add the `SrcFile` property when creating the parent component for the root `pyproject.toml`.
```tmpParentComponent.properties = tmpParentComponent.properties || [];
tmpParentComponent.properties.push({
name: "SrcFile",
value: pyProjectFile,
});
```
- This mirrors how workspace `pyproject.toml` files are handled in lib/helpers/utils.js.
Reproduced the crash with …
=> Fix undefined SrcFile for root pyproject.toml causing crash in postgen.js (#2236)

.github/workflows/binary-builds.yml, lib/cli/index.js
PHP and ruby were not in the SBOM, because they were not working in the workflows. I made some changes and added them back now:
- Changed the images for the linux build to php-images
- Installed composer for Darwin and Linux
- Fixed the call that checks for composer on Windows
=> Re-added php and ruby to the binary SBOMs

ci/images/Dockerfile.java11, ci/images/Dockerfile.java17, ci/images/Dockerfile.java17-slim, ci/images/Dockerfile.node20, ci/images/Dockerfile.python311, ci/images/Dockerfile.python312, ci/images/Dockerfile.python313, ci/images/Dockerfile.python36, ci/images/opensuse/Dockerfile.python310, ci/images/opensuse/Dockerfile.python39, ci/images/opensuse/Dockerfile.rolling
Bazelisk installs itself as the binary `bazel` and will download the actual bazel when called. The default URL is on GitHub, which we already had proxied in Nexus.
=> Bazel can also be downloaded from Nexus when running on self-hosted

.github/workflows/repotests.yml, lib/cli/index.js, lib/helpers/utils.js, lib/helpers/utils.poku.js, lib/stages/postgen/postgen.js, types/helpers/utils.d.ts, types/lib/helpers/utils.d.ts
Add yarn workspaces support, I focused on classic yarn (yarn 1).
The logic mainly parses package.json to extract list of workspaces, parse them and build list of workspace components (if they have `package.json`, add them as standalone components, then use that map to build the dependencies array as well.
I followed pnpm and uv workspace parsing logic.
While testing, I've noticed that adding `--evidence`  was leading to duplicate properties like `cdx:bom:componentNamespaces`, `cdx:bom:componentTypes` and `cdx:bom:componentNamespaces`, which is why I added the if condition to only add the properties if they don't exist.
Sample command that caused the problem.
`cdxgen -t yarn -o sbom.json . --no-recurse --no-babel --evidence`
=> Add yarn workspace support

lib/cli/index.js
This seems to fix the issue with spawnSync npm install: https://github.com/CycloneDX/cdxgen/issues/2388
=> Fix issue 2388: spawnSync npm ENOENT error

ci/images/opensuse/Dockerfile.rolling
OpenSuse just dropped java24 from the tumbleweed repos and replaced it with 25.
=> Tumbleweed replaced java24 with 25

ci/Dockerfile, ci/Dockerfile-deno, renovate.json
As per https://github.com/CycloneDX/cdxgen/pull/2420#issuecomment-3374168126
=> build(renovate): disable digest pins for cyclonedx/cdxgen-ruby-builder
