CycloneDX/cdxgen

- README.md
- bin/cdxgen
- index.js
- package.json
- utils.js
- utils.test.js
php
ruby
Increase jest timeout
Improve csproj
fixes #24
> Support recurse option for more languages

- bin/cdxgen
- package.json
> Added HTTP proxy support

- README.md
- index.js
- license-mapping.json
- package.json
- utils.js
- vendor-alias.json
To support Bom generation, the war file is
- Exploded to a temp directory. Iterate for each jar file from the WEB-INF/lib directory and extract it.
- Search for pom.xml in the META-INF directory. If available use that to extract metadata (Works for most jars. Accurate)
- As a fallback try to guess the properties from META-INF/MANIFEST.MF file (Legacy jars low accuracy)
- Query maven central to populate values that might be missing for certain packages
- Generate BoM
Tested with few wars.
> Generate BoM from war file

- index.js
Since version 2, the composer "update" command can also create a lockfile, using the --no-install option.
Resolves #103
> Use composer 2 ability to create lockfile without installing.

- utils.js
Add "dev" dependencies with scope = "optional".
Side effect: normal dependencies get scope = "required".
> Add PHP composer dev dependencies

- index.js
Copy-pasted existed code and made some name changes. Let me know if this isn't acceptable or if I should try to DRY it out
Should resolve https://github.com/AppThreat/cdxgen/issues/111
> Fix multiple poetry.lock files

- index.js
> Fix call to parse PubYamlData

- bin/cdxgen
- index.js
Fixes: https://github.com/AppThreat/cdxgen/issues/156
Ideally, parsers in https://github.com/AppThreat/cdxgen/blob/v4.0.34/utils.js would also fail on error as well.
> Introduce fail-on-error argument to fail on errors

- .github/workflows/dockertests.yml
- README.md
- binary.js
- package-lock.json
- package.json
This PR changes the plugins namespace to cyclonedx from appthreat
Signed-off-by: Prabhu Subramanian <prabhu@appthreat.com>
> Use cyclonedx plugins

- README.md
needed to revert some changes i made via #237.
fixes https://github.com/CycloneDX/cdxgen/pull/237#pullrequestreview-1295960431
> docs: fix markdown code fence blocks language

- README.md
- index.js
- utils.js
- utils.test.js
Plus set scope to required for direct dependencies.
> Invoke pip freeze automatically for python

- .github/workflows/npm-release.yml
Fixes https://github.com/CycloneDX/cdxgen/issues/264
> ARM 64 container image

- bin/cdxgen
- index.js
- test/data/golist-dep.txt
- utils.js
- utils.test.js
Fixes https://github.com/CycloneDX/cdxgen/issues/302
> Use name attribute for go

- .github/workflows/repotests.yml
- README.md
- index.js
- utils.js
wondered, why npm analysis lasted so long in our projects... reason was `FETCH_LICENSE=false` was configured but did not work as expected.
Now the boolean parameters should all work the same way.
> Convenient boolean configuration

- .github/workflows/dockertests.yml
- .github/workflows/repotests.yml
- README.md
- binary.js
- docker.js
- index.js
- test/data/gradle-out-249.dep
- utils.js
- utils.test.js
@ajmalab Could you kindly test this branch and let me know how it looks?
> Fixes #249 and #315

- test/data/gradle-core.out
- test/data/gradle-s.out
- test/data/gradle-service.out
- utils.js
- utils.test.js
Fixes #318 and "undefined" ref bug
> Handles a case where a gradle dependency

- index.js
- utils.js
- utils.test.js
@heubeck Could you kindly test this PR and let me know how it looks?
> Attempt to fix #320

- index.js
- test/data/gradle-properties-single2.txt
- utils.js
- utils.test.js
Fixes the incorrect purl type reported with https://github.com/CycloneDX/cdxgen/issues/328#issuecomment-1568791384
Fixes the parent component getting duplicated issue
https://github.com/CycloneDX/cdxgen/issues/328#issuecomment-1568807333
> Bug fix with purl types

- index.js
> #348 exclude java qualifier from resulting bom

- .github/workflows/app-release.yml
- .github/workflows/nodejs.yml
- .gitignore
- README.md
- package-lock.json
- package.json
- utils.test.js
```
software provenance refers to the verifiable information regarding the origin of a software configuration item; the development facility or the location where it was developed
```
> Replace pkg with caxa

- data/lic-mapping.json
- utils.js
- utils.test.js
> Cache nuget metadata lookup with some safe defaults

- .github/workflows/python-atom-tests.yml
- contrib/bom-validate.py
- data/pypi-pkg-aliases.json
- utils.js
Makes cdxgen attempt a pip freeze for all virtual environments
@anthonyharrison, could you kindly test with this branch?
> Fixes #375

- .github/workflows/repotests.yml
- README.md
- bin/cdxgen.js
- index.js
@dorjecurreli could you kindly test and review this PR?
> Pass --no-recurse to disable recursive lookup

- index.js
- utils.js
- validator.js
@ajmalab Kindly test and review this PR.
> Fixes #399 and #401

- index.js
- package-lock.json
- package.json
- utils.js
Fixes https://github.com/CycloneDX/cdxgen/issues/406
> Decode encoded purl before assigning to key in sbom

- index.js
updated the index.js to fix the issue https://github.com/CycloneDX/cdxgen/issues/403
> BugFix 403

- contrib/piptree.py
- piptree.js
Corrected parsing of package name and version.
> Fixed editable dependency issue

- .github/workflows/npm-release.yml
- contrib/free_disk_space.sh
> Trim CI agents

- README.md
- index.js
- utils.js
Resolves https://github.com/CycloneDX/cdxgen/issues/423
> Issue #423: Introduce separate ENVs for different gradle tasks

- index.js
Fixes #443 using quick option 1
Let's do license to licenses conversion later.
> Fixes #443 using quick option 1

- index.js
@ajmalab Could you kindly test this branch with multiple gradle projects?
> Fixes #417. Adds support for nested sub-projects

- index.js
- package-lock.json
- package.json
> Update packages and bump version

- .github/workflows/repotests.yml
- README.md
- bin/repl.js
- display.js
- docker.js
- docker.test.js
- package-lock.json
- package.json
```shell
node bin/repl.js
```
Use the instructions in the readme.
> cdxgen interactive repl

- ADVANCED.md
- README.md
- bin/evinse.js
- bin/repl.js
- db.js
- display.js
- evinser.js
- index.js
- package-lock.json
- package.json
- test/data/ivy-2.11.0.xml
- utils.js
Let's focus on only java with gradle projects to start with.
```shell
git clone https://github.com/CycloneDX/cdxgen
git checkout feature/evinse-gradle
npm install
export CDXGEN_DEBUG_MODE=debug
cd <path to code>
mvn compile
node bin/cdxgen.js -t java -o bom.json <path to code>
node bin/evinse.js -i bom.json -o bom.evinse.json <path to code>
node bin/repl.js bom.evinse.json
```
> Evinse support for java with gradle project - part 2

- analyzer.js
- bin/evinse.js
- evinser.js
- index.js
- utils.js
Tested with video.js
Fixes #474
> Evinse for js

- ADVANCED.md
- binary.js
- data/queries-win.json
- data/queries.json
- display.js
- evinser.js
- index.js
- package-lock.json
- package.json
- utils.js
- utils.test.js
This PR includes:
To test OBoM generation on amd64 and arm64 for Windows and Linux hosts.
```shell
git clone https://github.com/CycloneDX/cdxgen
cd cdxgen
npm install
node bin/cdxgen.js -t os -o bom.json
```
To test SaaSBoM generation for Java
```shell
git clone https://github.com/CycloneDX/cdxgen
cd cdxgen
npm install
node bin/cdxgen.js -t java -o bom.json <repo path>
node bin/evinse.js -i bom.json -o bom.evinse.json -l java <repo path>
```
To test granular signing/verification.
```shell
git clone https://github.com/CycloneDX/cdxgen
cd cdxgen
npm install
node bin/cdxgen.js -o bom.json --generate-key-and-sign <repo path>
node bin/verify.js -i bom.json --public-key public.key
```
> Few adhoc bug fixes. 9.7.0 prep

- README.md
relates to:
- https://github.com/Homebrew/homebrew-core/pull/140508
> feat: add homebrew installation note

- .github/workflows/app-release.yml
- .github/workflows/appimage.yml
- .github/workflows/dockertests.yml
- .github/workflows/python-atom-tests.yml
- .github/workflows/repotests.yml
- remove ci skip per https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
- update to use latest ubuntu runner.
> chore: improve github action setup

- index.js
- package-lock.json
> Retain parent component in universal mode

- README.md
- index.js
- test/data/bazel/bazel-action-graph.txt
- utils.js
- utils.test.js
This allows SBOM generation for specific Bazel targets. Can be activated using `BAZEL_USE_ACTION_GRAPH` env variable.
Addresses https://github.com/CycloneDX/cdxgen/issues/531
> feat: alternative bazel strategy

- test/data/project.assets.json
- utils.js
- utils.test.js
Please see the discussion [here](https://github.com/CycloneDX/cdxgen/pull/532#issuecomment-1712409577) for the background on this ticket.
This PR builds off https://github.com/CycloneDX/cdxgen/pull/532 by adding direct .NET pkg dependencies
cc: @prabhu @cerrussell
> .NET Direct Pkg Dependencies

- README.md
- bin/cdxgen.js
- index.js
Add argument to accept parent UUID from the user and add that parent UUID in the bompayload with if else condition
> Fix for #549

- test/data/gradle-dependencies-559.txt
- test/data/gradle-properties-559.txt
- utils.js
- utils.test.js
Fixes #559 by checking project names are more than a character long.
@heubeck
> Fixes #559

- utils.js
> Test maven wrapper before use

- server.js
Add dependency track publish support when using cdxgen in server-mode.
Verified locally against a running dtrack instance
> feat(server): support dtrack publishing

- README.md
- docs/SERVER.md
- docs/_sidebar.md
WIP - add table for server arguments
> docs: add server arguments

- package-lock.json
- package.json
To help with previewing docsify output locally
> build: add docs script

- docs/SERVER.md
Fix table formatting for https://cyclonedx.github.io/cdxgen/#/SERVER?id=server-arguments
> docs: fix table formatting

- index.js
- utils.js
> Bug fix. Reuse usages slices file for python parsedeps invocation

- README.md
- index.js
- utils.js
- utils.test.js
Expands #611 by adding dependency trees.
> Add dependency tree for paket.lock files

- index.js
- utils.js
If group is empty use name as group.
Try to fetch missing metadata from maven (including licence information when FETCH_LICENSE is set) for standalone Jar files.
Steps to reproduce:
1. Download [wsdl4j-1.6.3.jar](https://repo1.maven.org/maven2/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar) and put it into empty folder.
2. Run cdxgen against this folder
Before my change:
```
"components": [
{
"group": "",
"name": "wsdl4j",
"version": "1.6.3",
"licenses": [],
"purl": "pkg:maven/wsdl4j@1.6.3?type=jar",
"type": "library",
"bom-ref": "pkg:maven/wsdl4j@1.6.3?type=jar",
"evidence": {
"identity": {
"field": "purl",
"confidence": 0.5,
"methods": [
{
"technique": "filename",
"confidence": 0.5,
"value": "wsdl4j-1.6.3.jar"
}
]
}
},
"properties": [
{
"name": "SrcFile",
"value": "wsdl4j-1.6.3.jar"
}
]
}
]
``` …
> Improved detection for standalone jar files

- analyzer.js
> Fixes #480

- bin/cdxgen.js
Fixes #673 
https://github.com/CycloneDX/cdxgen/issues/673#issuecomment-1788084173
> Force version argument to be a string

- .github/workflows/java-reachables-test.yml
- bin/cdxgen.js
- docs/LESSON1.md
- docs/LESSON2.md
- docs/_sidebar.md
- evinser.js
- index.js
- package-lock.json
- package.json
- utils.js
Pass --exclude "glob pattern" to ignore application-specific directories. It can be used multiple times and specified in config files.
- Performance improvements related to https://github.com/CycloneDX/cdxgen/issues/687
> Support for excluding directories. Tweaks to cache jar namespaces

- .github/workflows/repotests.yml
Temporarily disable step ha-android to check if all other steps complete successfully
> Disabe step ha-android

- README.md
- index.js
- package-lock.json
- package.json
- test/data/packages2.lock.json
- test/data/packages3.lock.json
- utils.js
- utils.test.js
Fixes #829 
https://github.com/ctaggart/froto
[out.txt](https://github.com/CycloneDX/cdxgen/files/14063972/out.txt)
Also tested with https://github.com/DamirsCorner/20220708-dotnet-nuget-lock
> dependency tree for dotnet packages.lock.json

- index.js
> dotnet dependency tree was getting lost without the type

- index.js
> Fixes #848

- index.js
> Fixes #848 in v10

- docs/ADVANCED.md
- envcontext.js
- envcontext.test.js
- index.js
- package.json
- utils.js
Build tools version can be collected with `--include-formulation`
cc: @heubeck
> Collect build context under formulation

- docker.js
- package-lock.json
- package.json
- utils.js
Handle maven search timeout
Fixes #852 in v9 release
Fixes https://github.com/CycloneDX/cdxgen/issues/855
> Ignore additional types during tar extraction. 

- docker.js
- utils.js
Fixes #852 https://github.com/CycloneDX/cdxgen/issues/855
@Albertoimpl, could you kindly test this branch?
> Ignore additional types during tar extraction

- .github/workflows/nodejs.yml
- docker.js
- index.js
- package-lock.json
- package.json
- utils.js
@Albertoimpl, could you kindly test with this branch?
> Native unzip

- package-lock.json
- package.json
- test/data/Gemfile4.lock
- utils.js
- utils.test.js
Example properties:
```
"properties": [
{
"name": "SrcFile",
"value": "/mnt/work/sandbox/photographer-io/Gemfile.lock"
},
{
"name": "cdx:gem:remote",
"value": "git://github.com/mceachen/closure_tree.git"
},
{
"name": "cdx:gem:remoteRevision",
"value": "a1613cc4741150efa1f24a5c8839d63671263e73"
}
]
```
> Track remote and revision for Gemfile.lock

- README.md
- docs/README.md
- docs/SERVER.md
> docs: add example for git authentication

- test/data/Package.resolved
- test/data/Package2.resolved
- utils.js
- utils.test.js
referenced issue: https://github.com/CycloneDX/cdxgen/issues/875
> Allow non-github urls and ssh urls

- test/data/pyproject_with_custom_poetry_source.toml
- utils.js
- utils.test.js
Solves an issue in python Poetry projects with custom sources. Issue #910
> Fix getting component name from pyproject.toml

- .eslintrc.cjs
- .github/workflows/npm-release.yml
- contrib/deno/README.md
- contrib/deno/deps.ts
- deno.json
- jsr.json
- package.json
- utils.js
@ajmalab big PR with a lot of refactoring coming up. Please wait for this PR to get merged before the gradle refactor work.
> Publish to jsr

- index.js
- utils.js
> dedups dependsOn from packages.lock.file

- utils.js
> resolve project reference for nuget without debug mode

- package-lock.json
- package.json
- utils.test.js
> Remove caxa

- deno.json
- index.js
- jsr.json
- package-lock.json
- package.json
- protobom.js
- protobom.test.js
- types/protobom.d.ts
- types/protobom.d.ts.map
Export proto support for 1.6 specification.
Fixes #971
> Export proto support for 1.6

- index.js
> Include cyclonedx-maven-plugin under tools for java

- biome.json
I believe you fixed these earlier today @prabhu.  Remove the override rules to downgrade severity
> chore(biome): remove unused rule overrides

- analyzer.js
- bin/repl.js
- bin/verify.js
- binary.js
- biome.json
- cbomutils.js
- display.js
- docker.js
- evinser.js
- index.js
- postgen.js
- protobom.test.js
- utils.js
- validator.js
> chore(biome): fix optional chaining cases

- bin/cdxgen.js
- biome.json
- display.js
- envcontext.js
- evinser.js
- index.js
- utils.js
- validator.js
https://biomejs.dev/linter/rules/no-double-equals/
> chore(biome): fix no double equals

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- utils.test.js
Limit vuln scan to required dependencies only
Fixes #1000
> Removed docsify which is not required for generating docs

- .github/workflows/repotests.yml
- utils.js
> Improve deno compatibility by using jar command fallback

- ci/Dockerfile
> [Fix] Docker Build fails almalinux:9.3

- .github/CODEOWNERS
Will help with automating reviewers for new PRs.  
LMK if there anyone else who should be added?
> build: add codeowners file

- docker.js
Enhancement based on discussion in https://owasp.slack.com/archives/C6R3R32H4/p1715682111519979
> feat(docker): default to docker.io registry

- ci/Dockerfile-bun
- ci/Dockerfile-deno
fixes: #1048 issue for Docker-deno and Docker-bun.
> Fix: Docker-deno and Docker-bun build fails

- bin/cdxgen.js
- bin/evinse.js
- bin/verify.js
- docs/CLI.md
Use full terminal width.  Don't limit to 80 chars
> feat: increase yargs terminal width

- analyzer.js
- biome.json
- package.json
- pnpm-lock.yaml
- utils.js
Update to biomejs 1.8.0.
Apply fixes
> build: update biomejs

- data/lic-mapping.json
Removed couple of incorrect expressions used for Apache-2.0
> Adds MIT-0

- ci/Dockerfile
- contrib/lima/cdxgen-opensuse.yaml
Having this globally improves the chances of `npm install` succeeding.
> Update node gyp to support python 3.12

- ci/Dockerfile-deno
> Fix: Add python alias to dockerfile-deno

- deno.json
- jsr.json
- lib/server/openapi.yaml
- package.json
- server.js
Related to https://github.com/apache/airflow/issues/40810
> Make type optional in server mode

- utils.js
* In case of multiple license expressions, unify them into one expression separated by OR conditional - more details in #1215
> Support multiple license expressions (#1215)

- .github/workflows/snapshot-tests.yml
- test/diff/README.md
- test/diff/diff_tests.py
- test/diff/requirements.txt
This PR specifies custom-json-diff~=1.5.5 to avoid breaking changes.
> Snapshot tests update

- package.json
configure `lint-staged` to perform biome fixes
> build: add lint-staged

- README.md
Match the server parameters as documented in docs/SERVER.md
> Update README.md - Server parameters

- .dockerignore
- .github/workflows/dockertests.yml
- .github/workflows/repotests.yml
- ci/Dockerfile
- ci/Dockerfile-ppc64
Let's see if this makes denotests work on windows
> use package import method in tests

- README.md
- deno.json
- docs/CLI.md
- docs/README.md
- jsr.json
- package.json
bump version of cdxgen to `10.9.11`.
> Doc: bump version to 10.9.11

- test/diff/diff_tests.py
- test/diff/requirements.txt
Updates the cjd version which has bugfixes related to version comparisons and the bom diff HTML report.
> Upgrade testing to use custom-json-diff v2.

- .github/workflows/build-base-images.yml
> Run "Upload base images" action only on main repository

- .github/workflows/snapshot-tests.yml
- test/diff/diff_tests.py
- test/diff/generate.py
- test/diff/repos.csv
Adds projects for the cdxgen testing matrix. 
#1470 needs to be merged first for tests to pass.
> Expand Python Snapshots

- contrib/cdxgenGPT/README.md
> Support image generation and parsing github url

- contrib/cdxgenGPT/README.md
- contrib/cdxgenGPT/cdxgen-for-bots.md
- docs/ml_profiles.md
- lib/stages/postgen/annotator.js
> cdxgen for bots

- ci/Dockerfile
- ci/Dockerfile-bun
- ci/Dockerfile-deno
- ci/base-images/cdxgen/Dockerfile.dotnet6
- ci/base-images/cdxgen/Dockerfile.dotnet7
- ci/base-images/cdxgen/Dockerfile.dotnet8
- ci/base-images/cdxgen/Dockerfile.dotnet9
- ci/base-images/cdxgen/Dockerfile.java
- ci/base-images/cdxgen/Dockerfile.java17
- ci/base-images/cdxgen/Dockerfile.node20
- ci/base-images/cdxgen/Dockerfile.python
- ci/base-images/cdxgen/Dockerfile.python310
- ci/base-images/cdxgen/Dockerfile.python311
- ci/base-images/cdxgen/Dockerfile.rolling
- ci/base-images/cdxgen/Dockerfile.ruby25
- ci/base-images/cdxgen/debian/Dockerfile.dotnet6
- ci/base-images/cdxgen/debian/Dockerfile.dotnet8
- ci/base-images/cdxgen/debian/Dockerfile.dotnet9
- ci/base-images/cdxgen/debian/Dockerfile.ruby33
- ci/base-images/cdxgen/debian/Dockerfile.ruby34
- ci/base-images/opensuse/Dockerfile.lang
> Introduce atom-tools to the container images

- lib/cli/index.js
> Set 'quarkus.dependency.sbom.schema-version' if spec version defined

- .github/workflows/repotests.yml
Moved some repo tests to the self-hosted Ubuntu agent. These are currently running on a Mac mini with some known issues with Java. So not a lot could be moved yet, but something for a start.
> repo tests quick

- .github/workflows/npm-release.yml
- .github/workflows/repotests.yml
- contrib/cloud-init.txt
- contrib/lima/cdxgen-ubuntu.yaml
We now have a new self-hosted ubuntu AMD64, a Beelink SER8 mini-pc with 32GB RAM and 1TB SSD. As an added bonus, the included AMD iGPU has 8GB VRAM and is able to run cdx1 with decent performance!
Demonstrates the `runs-on` attribute to utilise this new agent.
> self hosted ubuntu

- ci/base-images/opensuse/Dockerfile.lang
- ci/base-images/opensuse/Dockerfile.python310
- ci/base-images/opensuse/Dockerfile.python39
OpenSuse updated OpenJDK from v23 to v24. Updated the Dockerfiles to reflect this.
> Updated OpenJDK to v24

- .github/workflows/nodejs.yml
- .github/workflows/repotests.yml
- deno.json
- jsr.json
- lib/cli/index.js
- package.json
- pnpm-lock.yaml
> Override jwa for node 24. Include node 24.x in workflow

- .github/workflows/image-build.yml
- .github/workflows/npm-release.yml
We need to find a way to extract the attachments to speed up the scanning.
> Attach cdx sboms to various images

- .github/workflows/build-images.yml
- ci/base-images/README.md
- ci/base-images/cdxgen/debian/Dockerfile.golang123
- ci/base-images/debian/Dockerfile.golang123
added container image for golang 1.23 just like we have for 1.24
> Add container image for golang 1.23

- ci/base-images/alpine/Dockerfile.java21
- ci/base-images/alpine/Dockerfile.java24
removed PYTHON_VERSION env var from alpine images
> Remove `PYTHON_VERSION` var from alpine images

- .github/workflows/binary-builds.yml
- .github/workflows/dockertests.yml
- .github/workflows/java-reachables-test.yml
- .github/workflows/nodejs.yml
- .github/workflows/npm-release.yml
- .github/workflows/nydus-demo.yml
- .github/workflows/repotests.yml
Align github action build steps to use node version 24
> build: align node versions

- .github/workflows/binary-builds.yml
Configured the binary-builds workflow to run on PRs as well.
> [build] Run binary-builds on PRs

- .github/workflows/binary-builds.yml
- .github/workflows/build-images.yml
- .github/workflows/build-rolling-image.yml
- .github/workflows/codeql.yml
- .github/workflows/dockertests.yml
- .github/workflows/fix-renovate-pnpm-checksum.yml
- .github/workflows/image-build.yml
- .github/workflows/java-reachables-test.yml
- .github/workflows/lint.yml
- .github/workflows/nodejs.yml
- .github/workflows/npm-release.yml
- .github/workflows/nydus-demo.yml
- .github/workflows/python-atom-tests.yml
- .github/workflows/rebuild-release-images.yml
- .github/workflows/repotests.yml
- .github/workflows/rerun-workflow.yml
- .github/workflows/snapshot-tests.yml
goal of this PR is to minimize the GitHub workflow permissions.
> chore: GH workflow permissions

- .github/workflows/binary-builds.yml
This fixes the last problems with creating and uploading a musl-arm64 binary during release.
> [build] Fixed issues with building/uploading musl-arm64 binary

- .github/workflows/binary-builds.yml
Instead of running everything in the container, only run the actual build inside and GH-actions outside
> [build] Only run build in container

- .github/workflows/binary-builds.yml
Simplified the separate binary-builds until they were almost the same. Then merged them into a single matrix.
Also updated to the latest runners, images and making sure node 24 is used on all of them.
> [build] Simplified and merged the binary builds

- .github/workflows/image-build.yml
- ci/images/debian/Dockerfile.dotnet10
- ci/images/debian/Dockerfile.dotnet6
- ci/images/debian/Dockerfile.dotnet8
- ci/images/debian/Dockerfile.dotnet9
Nexus also supports NuGet, so I added that for self-hosted runners as well.
> [build] Using Nexus for NuGet packages on self-hosted runners

- .github/workflows/image-build.yml
- ci/images/opensuse/Dockerfile.python310
- ci/images/opensuse/Dockerfile.python39
- ci/images/opensuse/Dockerfile.rolling
Nexus supports YUM repositories as well, so I added OpenSuse's repos and configured our images to use these repos when being built on self-hosted runners.
> [build] Added usage of Nexus for OpenSuse when running on self-hosted runners

- .github/workflows/image-build.yml
- ci/images/debian/Dockerfile.dotnet10
- ci/images/debian/Dockerfile.dotnet6
- ci/images/debian/Dockerfile.dotnet8
- ci/images/debian/Dockerfile.dotnet9
- ci/images/debian/Dockerfile.golang123
- ci/images/debian/Dockerfile.golang124
- ci/images/debian/Dockerfile.php83
- ci/images/debian/Dockerfile.php84
- ci/images/debian/Dockerfile.ruby26
- ci/images/debian/Dockerfile.ruby33
- ci/images/debian/Dockerfile.ruby34
- ci/images/debian/Dockerfile.rust1
- ci/images/debian/Dockerfile.swift6
Added APT repositories to Nexus and added them in our Images when run on self-hosted runners.
> [build] Added usage of Nexus for Debian when running on self-hosted runners

- .github/workflows/image-build.yml
- ci/images/Dockerfile.dotnet7
- ci/images/Dockerfile.dotnet8
- ci/images/Dockerfile.dotnet9
- ci/images/Dockerfile.java11
- ci/images/Dockerfile.java17
- ci/images/Dockerfile.java17-slim
- ci/images/Dockerfile.node20
- ci/images/Dockerfile.python311
- ci/images/Dockerfile.python312
- ci/images/Dockerfile.python313
- ci/images/Dockerfile.python36
- ci/images/Dockerfile.ruby25
And now we also get our Suse packages from Nexus when running on self-hosted.
> [build] Added usage of Nexus for Suse when running on self-hosted runners

- ci/images/debian/Dockerfile.dotnet10
- ci/images/debian/Dockerfile.dotnet6
- ci/images/debian/Dockerfile.dotnet8
- ci/images/debian/Dockerfile.dotnet9
- ci/images/debian/Dockerfile.golang123
- ci/images/debian/Dockerfile.golang124
- ci/images/debian/Dockerfile.php83
- ci/images/debian/Dockerfile.php84
- ci/images/debian/Dockerfile.ruby26
- ci/images/debian/Dockerfile.ruby33
- ci/images/debian/Dockerfile.ruby34
- ci/images/debian/Dockerfile.rust1
- ci/images/debian/Dockerfile.swift6
Probably a copy-paste error, parameters where the wrong way around!
> Reverting the Debian repos on self-hosted was not correct

- .github/workflows/image-build.yml
- ci/images/Dockerfile.dotnet7
- ci/images/Dockerfile.dotnet8
- ci/images/Dockerfile.java11
- ci/images/Dockerfile.java17
- ci/images/Dockerfile.java17-slim
- ci/images/Dockerfile.node20
- ci/images/Dockerfile.python311
- ci/images/Dockerfile.python312
- ci/images/Dockerfile.python313
- ci/images/Dockerfile.python36
- ci/images/debian/Dockerfile.dotnet10
- ci/images/debian/Dockerfile.dotnet6
- ci/images/debian/Dockerfile.dotnet8
- ci/images/debian/Dockerfile.dotnet9
- ci/images/debian/Dockerfile.golang123
- ci/images/debian/Dockerfile.golang124
- ci/images/debian/Dockerfile.php83
- ci/images/debian/Dockerfile.php84
- ci/images/debian/Dockerfile.ruby26
- ci/images/debian/Dockerfile.ruby33
- ci/images/debian/Dockerfile.ruby34
- ci/images/debian/Dockerfile.rust1
- ci/images/debian/Dockerfile.swift6
- ci/images/debian/install.sh
- ci/images/opensuse/Dockerfile.python310
- ci/images/opensuse/Dockerfile.python39
- ci/images/opensuse/Dockerfile.rolling
> Added usage of Nexus for downloading binaries (releases) from GitHub when running on self-hosted runners

- .github/workflows/image-build.yml
- ci/images/debian/Dockerfile.swift6
> Added usage of Nexus for downloading Swift when running on self-hosted runners

- .github/workflows/image-build.yml
- ci/images/alpine/Dockerfile.php84
- ci/images/debian/Dockerfile.php83
- ci/images/debian/Dockerfile.php84
> Added usage of Nexus for downloading Composer when running on self-hosted runners

- .github/workflows/binary-builds.yml
- .github/workflows/dockertests.yml
- .github/workflows/fix-renovate-pnpm-checksum.yml
- .github/workflows/image-build.yml
- .github/workflows/java-reachables-test.yml
- .github/workflows/lint.yml
- .github/workflows/nodejs.yml
- .github/workflows/npm-release.yml
- .github/workflows/python-atom-tests.yml
- .github/workflows/repotests.yml
- .github/workflows/test-nodejs-nightly.yml
- lib/helpers/utils.poku.js
This should make usage of 'corepack' obsolete and make us future-proof when it gets removed from the core.
> Added action 'pnpm/action-setup' to install pnpm

- .github/workflows/repotests.yml
Removed as part of https://github.com/CycloneDX/cdxgen/pull/2296
> fix: remove unused env var

- renovate.json
Re-enabling dockerfile updates based on discussions in https://github.com/CycloneDX/cdxgen/pull/2291
> chore(renovate): configure dockerfile minor, patch, pin, digest

- .github/workflows/nodejs.yml
- .versions/node_20
- .versions/node_21
- .versions/node_22
- .versions/node_23
- .versions/node_24
- renovate.json
To be able to update nodejs versions in a github matrix, I added several files for all versions we want to test. Each file contains only a specific version of node for the major-version contained in its name.
This PR sets the versions to the x.0.0 releases, so we can test renovate after merging.
> Reading node versions for matrix from files

- renovate.json
> Revert "config(renovate): docker pin digest"

- .versions/gradle_8
- .versions/gradle_9
- ci/images/Dockerfile.java11
- ci/images/Dockerfile.java17
- ci/images/Dockerfile.java17-slim
- ci/images/opensuse/Dockerfile.rolling
- ci/images/temurin/Dockerfile.java21
- ci/images/temurin/Dockerfile.java24
- ci/images/temurin/Dockerfile.java8
Created version-files for gradle, reset the base-line and added ARGS in Dockerfiles
> Created version-files for gradle
